version: '3.9'

################################################################################

x-app: &app
  build: &app-build
    context: .
    dockerfile: Dockerfile.app
  profiles:
    - app
  command:
    - app
  restart: unless-stopped
  depends_on:
    - kafka-1
    - kafka-2
    - kafka-3

x-producer: &producer
  <<: *app
  environment:
    KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    KAFKA_PAYMENTS_TOPIC: payments
  build:
    <<: *app-build
    args:
      BUILD_TARGET: producer

x-aggregator: &aggregator
  <<: *app
  environment:
    KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    KAFKA_PAYMENTS_TOPIC: payments
    KAFKA_AGGREGATED_PAYMENTS_TOPIC: aggregated_payments
    KAFKA_AGGREGATORS_GROUP: aggregators
    KAFKA_TUMBLING_WINDOW_SIZE: 60000000000 # 1 minute (in nanoseconds)
  build:
    <<: *app-build
    args:
      BUILD_TARGET: aggregator

x-consumer: &consumer
  <<: *app
  environment:
    KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    KAFKA_AGGREGATED_PAYMENTS_TOPIC: aggregated_payments
    KAFKA_AGGREGATED_PAYMENTS_GROUP: aggregated_payments_consumers
  build:
    <<: *app-build
    args:
      BUILD_TARGET: consumer

x-kafka: &kafka
  image: bitnami/kafka:latest
  environment: &kafka-env
    KAFKA_ENABLE_KRAFT: yes
    KAFKA_CFG_PROCESS_ROLES: broker,controller
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
    ALLOW_PLAINTEXT_LISTENER: yes
    KAFKA_KRAFT_CLUSTER_ID: WvadtsIlSMCz8l2rtf-rcQ

x-redpanda-console: &redpanda-console
  image: docker.redpanda.com/redpandadata/console:${REDPANDA_CONSOLE_VERSION}
  entrypoint: /bin/sh
  command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
  environment:
    CONFIG_FILEPATH: /tmp/config.yml
    CONSOLE_CONFIG_FILE: |
      kafka:
        brokers: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]
        schemaRegistry:
          enabled: false
          urls: ["http://redpanda-0:8081"]
  ports:
    - ${REDPANDA_CONSOLE_PORT}:8080
  depends_on:
    - kafka-1
    - kafka-2
    - kafka-3

################################################################################

services:
  # producers
  producer-1:
    <<: *producer
    container_name: producer-1
  producer-2:
    <<: *producer
    container_name: producer-2
  producer-3:
    <<: *producer
    container_name: producer-3

  # aggregator
  aggregator:
    <<: *aggregator
    container_name: aggregator

  # consumer
  consumer:
    <<: *consumer
    container_name: consumer

  # redpanda console ui
  ui:
    <<: *redpanda-console
    container_name: kafka-ui

  # kafka nodes
  kafka-1:
    <<: *kafka
    container_name: kafka-1
    ports:
      - 19092:19092
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: HOST://0.0.0.0:19092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: HOST://localhost:19092,PLAINTEXT://kafka-1:9092
    volumes:
      - kafka-1:/bitnami/kafka
  kafka-2:
    <<: *kafka
    container_name: kafka-2
    ports:
      - 29092:29092
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: HOST://0.0.0.0:29092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: HOST://localhost:29092,PLAINTEXT://kafka-2:9092
    volumes:
      - kafka-2:/bitnami/kafka
  kafka-3:
    <<: *kafka
    container_name: kafka-3
    ports:
      - 39092:39092
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_LISTENERS: HOST://0.0.0.0:39092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: HOST://localhost:39092,PLAINTEXT://kafka-3:9092
    volumes:
      - kafka-3:/bitnami/kafka

################################################################################

volumes:
  kafka-1:
  kafka-2:
  kafka-3: